<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0c7116a8-02d0-4c5b-8b3a-71f881d117f8</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.GenAI" Version="1.2.0" />
		<PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-rc2" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="skills\expense-report\assets\expense-report-template.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="skills\expense-report\references\POLICY_FAQ.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="skills\expense-report\SKILL.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	
</Project>
